apiVersion: apps/v1
kind: Deployment
metadata:
  name: javaapp
  labels:
    app: javaapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: javaapp
  template:
    metadata:
      labels:
        app: javaapp
    spec:
      containers:
      - name: javaapp
        image: naveennk1999/spring-boot-mongo
        ports:
        - containerPort: 8080
        resources:
          requests:
             cpu: 500m
          limits:
             cpu: 1

---

apiVersion: v1
kind: Service
metadata:
  name: java
spec:
  type: NodePort
  selector:
    app: javaapp
  ports:
  - name: javaapp
    port: 80
    targetPort: 8080
